# Generated by Django 4.1 on 2022-09-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyWishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_film', models.BooleanField()),
                ('title_film', models.CharField(max_length=50)),
                ('rating_film', models.IntegerField()),
                ('release_date_film', models.TextField()),
                ('review_film', models.TextField()),
            ],
        ),
    ]
