# Generated by Django 4.1 on 2022-09-20 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mywishlistitem',
            old_name='status_film',
            new_name='status_watched_film',
        ),
    ]
