# Generated by Django 4.1 on 2022-09-20 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_rename_status_film_mywishlistitem_status_watched_film'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyWishlistItem',
            new_name='MyWatchlistItem',
        ),
    ]
